version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - ./mongodb/:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  php:
    image: php:7.4-apache
    container_name: php
    ports:
      - "80:80"
    volumes:
      - /home/dataproc/server-cats/:/var/www/html
    links:
      - mysql
      - mongo